# Generated by Django 4.0.3 on 2022-03-19 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=255)),
                ('importance_level', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.PositiveIntegerField(unique=True)),
                ('email', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Performance_Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('study_hours', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('total_scores', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=255)),
                ('mental_state', models.CharField(blank=True, max_length=255, null=True)),
                ('acidity_level', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_crud.user')),
            ],
        ),
        migrations.CreateModel(
            name='Mental_Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('energy_level', models.IntegerField(blank=True, null=True)),
                ('mental_state', models.CharField(blank=True, max_length=255, null=True)),
                ('acidity_level', models.CharField(blank=True, max_length=255, null=True)),
                ('day_going', models.CharField(blank=True, max_length=255, null=True)),
                ('feeling', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_crud.user')),
            ],
        ),
    ]
