# Generated by Django 4.0.3 on 2022-03-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance_forms',
            name='acidity_level',
        ),
        migrations.RemoveField(
            model_name='performance_forms',
            name='mental_state',
        ),
    ]
